PR Review for video library app
Janaki2399/Dhrutham-Play pull request #1
Opened 2021-04-15 13:56 UTC by Janaki2399

Name : Janaki S
Live Link:https://dhrutham-play.netlify.app/
Here is the initial version (just the front end). Please Review it let me know your feedback

2021-04-18 14:29 UTC, Xdev200 requested changes

2021-04-18 14:29 UTC, Xdev200 commented on src/contexts/data-context.js
> +const dataContext = createContext();
Use Capital letter for context name.

2021-04-18 14:29 UTC, Xdev200 commented on src/contexts/data-context.js
> +    allVideos:allVideoData,
Use proper key value name

2021-04-18 14:29 UTC, Xdev200 commented on src/App.js
> +import { CategoryItem } from './Components/Category/CategoryItem';
unused import, you can remove this

2021-04-18 15:37 UTC, kushanksriraj requested changes

2021-04-18 15:37 UTC, kushanksriraj commented on src/App.js
> +import { Category } from './Components/Category/Category';
Use Prettier or alike VS code extension for auto formatting.

2021-04-18 15:37 UTC, kushanksriraj commented on src/Components/Category/Category.js
> +export function Category() {
use ES6 functions

2021-04-18 15:37 UTC, kushanksriraj commented on src/Components/Library/Library.js
> +              isUserPlayList={index === 0 ? false : true}
Use the value returned from the boolean expression rather than true and false explicitly.

2021-04-18 15:37 UTC, kushanksriraj commented on src/Components/VideoList/VideoListPage.js
> +      ? selectedCategoryObject.list[0].videoId
Use conditional chaining here.

2021-04-18 15:37 UTC, kushanksriraj commented on src/Components/LikeButton.js
> +  function getVideoObject(id){
Extract this as a utility function.

2021-05-05 16:22 UTC, Xdev200 commented on src/Components/Category/Category.js
> +      {categoryPlayListData.map((categoryItem) => {
You can destructure the object {id,categoryItem}

2021-05-05 16:25 UTC, Xdev200 commented on src/Components/Category/CategoryItem.js
> +export function CategoryItem({ categoryItem, isUserPlayList }) {
the function name should follow camelCase.

2021-05-05 16:26 UTC, Xdev200 commented on src/Components/Category/CategoryItem.js
> +      style={{ maxWidth: "15rem" }}
Avoid inline style

2021-05-05 16:31 UTC, Xdev200 commented on src/Components/Library/Library.js
> +              isUserPlayList={index === 0 ? false : true}
you can use this:  index?true:false instead of index === 0 ? false: true

2021-05-05 16:34 UTC, Xdev200 commented on src/App.js
> +import { Category } from './Components/Category/Category';
Use Prettier

2021-05-05 16:36 UTC, Xdev200 requested changes
I have reviewed

2021-05-06 11:56 UTC, Amarjit-Singh-1 commented
The App looks Great! I would suggest some changes:
1. I see you have used inline styling at many places. Try to avoid it.
2. Change the title in the index.html file

2021-05-06 13:08 UTC, Janaki2399 commented on src/Components/Category/CategoryItem.js
> +export function CategoryItem({ categoryItem, isUserPlayList }) {
No,this is a component.So have used full capital

2021-05-09 13:39 UTC, Janaki2399 commented on src/contexts/data-context.js
> +const dataContext = createContext();
Done

2021-05-09 13:42 UTC, Janaki2399 commented on src/contexts/data-context.js
> +    allVideos:allVideoData,
Done

2021-05-09 13:42 UTC, Janaki2399 commented on src/App.js
> +import { Category } from './Components/Category/Category';
Okay

2021-05-09 13:43 UTC, Janaki2399 commented on src/App.js
> +import { CategoryItem } from './Components/Category/CategoryItem';
Okay done

2021-05-09 13:44 UTC, Janaki2399 commented on src/Components/Library/Library.js
> +              isUserPlayList={index === 0 ? false : true}
Done

2021-05-09 13:52 UTC, Janaki2399 commented on src/Components/Category/Category.js
> +      {categoryPlayListData.map((categoryItem) => {
Done

2021-05-09 13:52 UTC, Janaki2399 commented on src/Components/Library/Library.js
> +              isUserPlayList={index === 0 ? false : true}
Done

2021-05-09 14:26 UTC, Janaki2399 commented
> The App looks Great! I would suggest some changes:
> 
> 1. I see you have used inline styling at many places. Try to avoid it.
> 2. Change the title in the index.html file

Done

2021-05-09 14:26 UTC, Janaki2399 commented on src/Components/Category/CategoryItem.js
> +      style={{ maxWidth: "15rem" }}
Done

2021-05-09 14:26 UTC, Janaki2399 commented on src/Components/LikeButton.js
> +  function getVideoObject(id){
I wouldn't need it if I integrate the backend.So will leave it for now

2021-05-09 14:28 UTC, Janaki2399 commented on src/Components/Category/Category.js
> +export function Category() {
I just checked Airbnb style guide, They have asked to use the normal function for the Component function.

2021-05-23 11:01 UTC, SurajGupta07 commented on src/App.js
> +          "https://dhrutham-play-backend.herokuapp.com/library"
URL can be stored in a variable and that can be used in all useEffects

2021-09-21 12:24 UTC, merged